# Generated by Django 4.2.4 on 2023-09-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score_threshold',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
