# Generated by Django 4.2.4 on 2023-09-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_score_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='job',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
