# Generated by Django 4.2.4 on 2023-09-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
